pub const MISSIONS: &[(&str, &str, u64)] = &[
    ("luigis_girls", "Luigi's Girls", 0x35B75C),
    (
        "dont_spank_ma_bitch_up",
        "Don't Spank Ma Bitch Up",
        0x35B76C,
    ),
    ("drive_misty_for_me", "Drive Misty For Me", 0x35B770),
    ("the_crook", "The Crook", 0x35B80C),
    ("the_thieves", "The Thieves", 0x35B810),
    ("the_wife", "The Wife", 0x35B814),
    ("her_lover", "Her Lover", 0x35B818),
    ("mike_lips_last_lunch", "Mike Lips Last Lunch", 0x35B780),
    (
        "farewell_chunky_lee_chong",
        "Farewell 'Chunky' Lee Chong",
        0x35B784,
    ),
    ("van_heist", "Van Heist", 0x35B788),
    ("ciprianis_chauffeur", "Cipriani's Chauffeur", 0x35B78C),
    ("taking_out_the_laundry", "Taking Out The Laundry", 0x35B79C),
    (
        "dead_skunk_in_the_trunk",
        "Dead Skunk in The Trunk",
        0x35B790,
    ),
    ("turismo", "Turismo", 0x35B838),
    ("the_getaway", "The Getaway", 0x35B794),
    ("the_pick_up", "The Pick-up", 0x35B7A0),
    ("patriot_playground", "Patriot Playground", 0x35B970),
    (
        "salvatores_called_a_meeting",
        "Salvatore's Called a Meeting",
        0x35B7A4,
    ),
    ("chaperone", "Chaperone", 0x35B7B4),
    ("cutting_the_grass", "Cutting The Grass", 0x35B7B8),
    (
        "triads_and_tribulations",
        "Triads and Tribulations",
        0x35B7A8,
    ),
    ("pump_action_pimp", "Pump Action Pimp", 0x35B774),
    ("diablo_destruction", "Diablo Destruction", 0x35B9EC),
    ("the_fuzz_ball", "The Fuzz Ball", 0x35B778),
    ("i_scream_you_scream", "I Scream You Scream", 0x35B7E4),
    ("trial_by_fire", "Trial by Fire", 0x35B7E8),
    ("bignveiny", "Big 'n Veiny", 0x35B7EC),
    ("mafia_massacre", "Mafia Massacre", 0x35B9F0),
    ("blow_fish", "Blow Fish", 0x35B7AC),
    ("bomb_da_base_act_i", "Bomb Da Base: Act I", 0x35B7BC),
    ("bomb_da_base_act_ii", "Bomb Da Base: Act II", 0x35B7C0),
    ("last_requests", "Last Requests", 0x35B7C4),
    ("sayonara_salvatore", "Sayonara Salvatore", 0x35B878),
    ("bling_bling_scramble", "Bling Bling Scramble", 0x35B8D4),
    ("under_surveillance", "Under Surveillance", 0x35B87C),
    ("kanbu_bust_out", "Kanbu Bust-out", 0x35B8AC),
    ("casino_calamity", "Casino Calamity", 0x35B9F8),
    ("grand_theft_auto", "Grand Theft Auto", 0x35B8B0),
    ("uzi_rider", "Uzi Rider", 0x35B8D8),
    ("multistorey_mayhem", "Multistorey Mayhem", 0x35B97C),
    ("paparazzi_purge", "Paparazzi Purge", 0x35B880),
    ("payday_for_ray", "Payday for Ray", 0x35B884),
    ("silence_the_sneak", "Silence The Sneak", 0x35B890),
    ("two_faced_tanner", "Two Faced Tanner", 0x35B888),
    ("deal_steal", "Deal Steal", 0x35B8B4),
    ("shima", "Shima", 0x35B8B8),
    ("smack_down", "Smack Down", 0x35B8BC),
    ("a_ride_in_the_park", "A Ride in the Park", 0x35B974),
    ("arms_shortage", "Arms Shortage", 0x35B894),
    ("evidence_dash", "Evidence Dash", 0x35B898),
    ("gone_fishing", "Gone Fishing", 0x35B89C),
    ("gangcar_round_up", "Gangcar Round Up", 0x35B8DC),
    ("plaster_blaster", "Plaster Blaster", 0x35B8A0),
    ("kingdom_come", "Kingdom Come", 0x35B8E0),
    ("liberator", "Liberator", 0x35B8C4),
    ("waka_gashira_wipeout", "Waka Gashira Wipeout", 0x35B8C8),
    ("a_drop_in_the_ocean", "A Drop in the Ocean", 0x35B8CC),
    ("grand_theft_aero", "Grand Theft Aero", 0x35B8FC),
    ("marked_man", "Marked Man", 0x35B8A4),
    ("escort_service", "Escort Service", 0x35B900),
    ("rumpo_rampage", "Rumpo Rampage", 0x35B9F4),
    ("uzi_money", "Uzi Money", 0x35B924),
    ("toyminator", "Toyminator", 0x35B928),
    ("rigged_to_blow", "Rigged to Blow", 0x35B92C),
    ("bullion_run", "Bullion Run", 0x35B930),
    ("bait", "Bait", 0x35B910),
    ("decoy", "Decoy", 0x35B904),
    ("loves_disappearance", "Love's Disappearance", 0x35B908),
    ("espresso_2_go", "Espresso-2-Go", 0x35B914),
    ("sam", "S.A.M", 0x35B918),
    ("the_exchange", "The Exchange", 0x35B948),
    ("rumble", "Rumble", 0x35B934),
    ("gripped", "Gripped", 0x35B978),
];

pub const COLLECTIBLES: &[(&str, &str, u64, u32)] = &[
    ("hidden_packages", "Hidden Packages", 0x35C3D4, 100),
    ("rampages", "Rampages", 0x35C0AC, 20),
    ("unique_stunt_jumps", "Unique Stunt Jumps", 0x35BFB0, 20),
];

pub const MISSION_TEXT: &[(&str, &str)] = &[
    ("luigis_girls", "LUIGI'S GIRLS"),
    ("dont_spank_ma_bitch_up", "DON'T SPANK MA BITCH UP"),
    ("drive_misty_for_me", "DRIVE MISTY FOR ME"),
    ("the_crook", "THE CROOK"),
    ("the_thieves", "THE THIEVES"),
    ("the_wife", "THE WIFE"),
    ("her_lover", "HER LOVER"),
    ("mike_lips_last_lunch", "MIKE LIPS LAST LUNCH"),
    ("farewell_chunky_lee_chong", "FAREWELL 'CHUNKY' LEE CHONG"),
    ("van_heist", "VAN HEIST"),
    ("ciprianis_chauffeur", "CIPRIANI'S CHAUFFEUR"),
    ("taking_out_the_laundry", "TAKING OUT THE LAUNDRY"),
    ("dead_skunk_in_the_trunk", "DEAD SKUNK IN THE TRUNK"),
    // JP calls this "ROAD RACING" instead of "TURISMO"
    ("turismo", "TURISMO"),
    ("the_getaway", "THE GETAWAY"),
    ("the_pick_up", "THE PICK-UP"),
    ("patriot_playground", "PATRIOT PLAYGROUND"),
    (
        "salvatores_called_a_meeting",
        "SALVATORE'S CALLED A MEETING",
    ),
    ("chaperone", "CHAPERONE"),
    ("cutting_the_grass", "CUTTING THE GRASS"),
    ("triads_and_tribulations", "TRIADS AND TRIBULATIONS"),
    ("pump_action_pimp", "PUMP-ACTION PIMP"),
    ("diablo_destruction", "DIABLO DESTRUCTION"),
    ("the_fuzz_ball", "THE FUZZ BALL"),
    ("i_scream_you_scream", "I SCREAM, YOU SCREAM"),
    ("trial_by_fire", "TRIAL BY FIRE"),
    ("bignveiny", "BIG'N'VEINY"),
    ("mafia_massacre", "MAFIA MASSACRE"),
    ("blow_fish", "BLOW FISH"),
    // JP calls these "BOMB DA BASE -ACT 1-" / "-ACT 2-"
    ("bomb_da_base_act_i", "BOMB DA BASE: ACT I"),
    ("bomb_da_base_act_ii", "BOMB DA BASE: ACT II"),
    ("last_requests", "LAST REQUESTS"),
    ("sayonara_salvatore", "SAYONARA SALVATORE"),
    ("bling_bling_scramble", "BLING-BLING SCRAMBLE"),
    ("under_surveillance", "UNDER SURVEILLANCE"),
    ("kanbu_bust_out", "KANBU BUST-OUT"),
    ("casino_calamity", "CASINO CALAMITY"),
    ("grand_theft_auto", "GRAND THEFT AUTO"),
    ("uzi_rider", "UZI RIDER"),
    ("multistorey_mayhem", "MULTISTOREY MAYHEM"),
    ("paparazzi_purge", "PAPARAZZI PURGE"),
    ("payday_for_ray", "PAYDAY FOR RAY"),
    ("silence_the_sneak", "SILENCE THE SNEAK"),
    ("two_faced_tanner", "TWO-FACED TANNER"),
    ("deal_steal", "DEAL STEAL"),
    ("shima", "SHIMA"),
    ("smack_down", "SMACK DOWN"),
    ("a_ride_in_the_park", "A RIDE IN THE PARK"),
    ("arms_shortage", "ARMS SHORTAGE"),
    ("evidence_dash", "EVIDENCE DASH"),
    ("gone_fishing", "GONE FISHING"),
    ("gangcar_round_up", "GANGCAR ROUND-UP"),
    ("plaster_blaster", "PLASTER BLASTER"),
    ("kingdom_come", "KINGDOM COME"),
    ("liberator", "LIBERATOR"),
    ("waka_gashira_wipeout", "WAKA-GASHIRA WIPEOUT!"),
    ("a_drop_in_the_ocean", "A DROP IN THE OCEAN"),
    ("grand_theft_aero", "GRAND THEFT AERO"),
    ("marked_man", "MARKED MAN"),
    ("escort_service", "ESCORT SERVICE"),
    ("rumpo_rampage", "RUMPO RAMPAGE"),
    ("uzi_money", "UZI MONEY"),
    ("toyminator", "TOYMINATOR"),
    ("rigged_to_blow", "RIGGED TO BLOW"),
    ("bullion_run", "BULLION RUN"),
    ("bait", "BAIT"),
    ("decoy", "DECOY"),
    ("loves_disappearance", "LOVE'S DISAPPEARANCE"),
    ("espresso_2_go", "ESPRESSO-2-GO!"),
    ("sam", "S.A.M."),
    ("the_exchange", "THE EXCHANGE"),
    ("rumble", "RUMBLE"),
    ("gripped", "GRIPPED!"),
];
