pub const MISSIONS: &[(&str, &str, &[(&str, &str, u32, bool)])] = &[
    (
        "CH1",
        "Chapter 1",
        &[
            (
                "M_1_01a",
                "Meet the Principal (Welcome to Bullworth)",
                0x1A,
                false,
            ),
            ("M_1_01b", "Bully Fight (Welcome to Bullworth)", 0x20, false),
            ("M_1", "Welcome to Bullworth", 0x26, true),
            ("M_1_02", "Mission Tutorial", 0x2C, false),
            ("M_1_03", "This is Your School", 0x32, true),
            ("M_1_04", "Get to Class", 0x38, false),
            ("M_1_05", "The Setup", 0x3E, true),
            ("M_1_06", "Slingshot", 0x4A, true),
            ("M_1_07", "Save Algie", 0x50, true),
            ("M_1_0E", "Peter's Errand", 0x8, false),
            ("M_1_08", "A Little Help", 0x56, true),
            ("M_1_09", "Defend Bucky", 0x7A, true),
            ("M_1_10", "That Bitch", 0x80, true),
            ("M_1_11", "The Candidate", 0x8C, true),
            ("M_1_12", "Halloween", 0x9E, true),
            ("M_1_13", "Help Gary", 0xBC, false),
            ("M_1_14", "Russell in the Hole", 0xC2, true),
        ],
    ),
    (
        "CH2",
        "Chapter 2",
        &[
            ("M_2_02", "Hattrick vs. Galloway", 0xEC, true),
            ("M_2_01", "Last Minute Shopping", 0xF2, true),
            ("M_2_03", "Prep Challenge", 0x182, true),
            // this has special logic
            (
                "M_2_03R",
                "Prep Challenge Rounds (1 - Chad, 2 - Justin, 3 - )",
                0xE6,
                false,
            ),
            ("M_2_04", "The Eggs", 0x10A, true),
            ("M_2_05", "Movie Tickets", 0x110, true),
            ("M_2_06", "Carnival Date", 0x116, true),
            ("M_2_07", "Race the Vale", 0x122, true),
            ("M_2_08", "Beach Rumble", 0x128, true),
            ("M_2_09", "Tad's House", 0x188, true),
            ("M_2_10", "Boxing Challenge", 0x194, false),
            ("M_2_11", "Dishonorable Fight", 0x19A, true),
        ],
    ),
    (
        "CH3",
        "Chapter 3",
        &[
            ("M_3_01", "Balls of Snow", 0x1CA, true),
            ("M_3_02", "Miracle on Bullworth St.", 0x1D0, true),
            ("M_3_03", "Christmas is Here", 0x1B2, true),
            ("M_3_04", "Nutcrackin'", 0x1D6, true),
            ("M_3_05", "Rudy the Red Nosed Santa", 0x1DC, true),
            ("M_3_06", "Jealous Johnny", 0x1E2, true),
            ("M_3_07", "Bait", 0x1E8, true),
            ("M_3_08", "Wrong Part of Town", 0x1F4, true),
            ("M_3_09", "Tagging", 0x1FA, true),
            ("M_3_10", "Lola's Race", 0x206, true),
            ("M_3_11", "The Tenements", 0x20C, true),
            ("M_3_12", "The Rumble", 0x212, false),
            ("M_3_13", "Fighting Johnny Vincent", 0x218, true),
        ],
    ),
    (
        "CH4",
        "Chapter 4",
        &[
            ("M_4_01", "Stronghold Assault", 0x236, true),
            ("M_4_02", "Nerd Boss Fight", 0x23C, true),
            ("M_4_03", "Funhouse Fun", 0x25A, true),
            ("M_4_04", "Paparazzi", 0x24E, true),
            ("M_4_05", "Defender of the Castle", 0x254, true),
            ("M_4_06", "Nice Outfit", 0x260, true),
            ("M_4_07", "Discretion Assured", 0x266, true),
            ("M_4_08", "The Big Game", 0x26C, false),
            ("M_4_09", "Jock Boss Fight", 0x272, true),
        ],
    ),
    (
        "CH5",
        "Chapter 5",
        &[
            ("M_5_01", "Making a Mark", 0x284, true),
            ("M_5_02", "Rats in the Library", 0x28A, true),
            ("M_5_03", "The Gym is Burning", 0x290, true),
            ("M_5_04", "Finding Johnny Vincent", 0x296, true),
            ("M_5_05", "Revenge on Mr. Burton", 0x2A2, true),
            ("M_5_06", "Preppies Vandalised", 0x2B4, true),
            ("M_5_07", "Go See The Principal", 0x2C6, true),
            ("M_5_08", "Busting In Part 1", 0x2CC, false),
            ("M_5_09", "Busting In Part 2", 0x2D2, false),
            ("M_5_10", "Showdown at the Plant", 0x2DE, true),
            ("M_5_11a", "Rescue Russell", 0x2E4, false),
            ("M_5_11b", "Take down the Clique Leaders", 0x2EA, false),
            ("M_5_11", "Final Showdown", 0x2F0, true),
        ],
    ),
    (
        "M_X",
        "Side Missions",
        &[
            ("M_X_01", "The Diary", 0x86, false),
            ("M_X_02", "Character Sheets", 0xB6, false),
            ("M_X_03", "The Big Prank", 0xAA, false),
            ("M_X_04", "Small Offences", 0x1A6, false),
            ("M_X_05", "Panty Raid", 0x11C, false),
            ("M_X_06", "Comic Klepto", 0x104, false),
            ("M_X_07", "Weed Killer", 0x18E, false),
            ("M_X_08", "Cook's Crush", 0x1BE, false),
            ("M_X_09", "Glass House", 0x1EE, false),
            ("M_X_10", "Discreet Deliveries", 0x21E, false),
            ("M_X_11", "Here's to you Ms. Philips", 0x22A, false),
            ("M_X_12", "Cook's Date", 0x230, false),
            ("M_X_13", "Galloway Away", 0x242, false),
            ("M_X_14", "Cheating Time", 0x27E, false),
            ("M_X_15", "Smash It Up", 0x2A8, false),
            ("M_X_16", "The Collector", 0x2AE, false),
            ("M_X_17", "Mailbox Armageddon", 0x2D8, false),
        ],
    ),
    (
        "M_X_T",
        "Transistors",
        &[
            ("M_X_LH2", "A Little Help 2", 0x5C, false),
            ("M_X_LH3", "A Little Help 3", 0x62, false),
            ("M_X_LH4", "A Little Help 4", 0x68, false),
            ("M_X_LH5", "A Little Help 5", 0x6E, false),
            ("M_X_LH6", "A Little Help 6", 0x74, false),
        ],
    ),
    (
        "M_C",
        "Clique Challenges",
        &[
            ("M_C_N", "Nerd Challenge", 0x1C4, false),
            ("M_C_G", "Greaser Challenge", 0x200, false),
            ("M_C_J", "Jocks Challenge", 0x248, false),
            ("M_C_T", "Townie Challenge", 0x29C, false),
        ],
    ),
    (
        "M_BX",
        "Boxing",
        &[
            ("M_BX_01", "Chad", 0xCE, false),
            ("M_BX_02", "Justin", 0xD4, false),
            ("M_BX_03", "Parker", 0xDA, false),
            ("M_BX_04", "Bryce", 0xE0, false),
        ],
    ),
    (
        "M_DB",
        "Dodgeball",
        &[
            ("M_DB_01", "vs. Team Prep", 0x3EC, false),
            ("M_DB_02", "vs. Team Greaser", 0x3F2, false),
            ("M_DB_03", "vs. Team Jock", 0x3F8, false),
            ("M_DB_04", "vs. Team Townie", 0x3FE, false),
        ],
    ),
    // only used for the watcher list, settings are added manually for this
    (
        "M_PR",
        "Paper Route",
        &[
            ("M_PR_01", "Intro", 0xF8, false),
            (
                "M_PR_D",
                "1 = 10 , 2 = 14 , 3 = 19 , 4 = 24 Deliveries",
                0xFE,
                false,
            ),
        ],
    ),
    (
        "M_LAWN",
        "Lawn Mowing",
        &[
            ("M_LAWN_01", "Park 1", 0x5D8, false),
            ("M_LAWN_02", "Park 2", 0x5DE, false),
            ("M_LAWN_03", "Park 3", 0x5E4, false),
            ("M_LAWN_04", "House 1", 0x5EA, false),
            ("M_LAWN_05", "House 2", 0x5F0, false),
            ("M_LAWN_06", "House 3", 0x5F6, false),
        ],
    ),
    (
        "MISC",
        "Misc",
        &[
            ("C_C_02", "Chapter 2 Cutscene", 0xC8, false),
            ("C_C_03", "Chapter 3 Cutscene", 0x1A0, false),
            ("C_C_04", "Chapter 4 Cutscene", 0x224, false),
            ("C_C_05", "Chapter 5 Cutscene", 0x278, false),
            ("C_C_C", "Credits", 0x2F6, false),
        ],
    ),
];

pub const ERRANDS_COUNT: u64 = 50;
pub const GNOMES_COUNT: u64 = 25;

pub const GNOMES_TOOLTIPS: [&str; 25] = [
    "Bullworth Town\nIn the hedges in front of Police HQ.",
    "Vale\nIn the bushy corner of the front of the church exterior.",
    "Vale\nTad's yard, near his gazebo.",
    "Vale\nTad's front yard, near a small vine-grown lattice.",
    "Blue Skies\nBackyard next to tattoo shop.",
    "Vale\nHappy Endings Retirement home, in the front yard near the pond.",
    "Vale\nNext to a mailbox at the house on the left\nafter the intersection leading from Bullworth Town bridge.",
    "Vale\nFront yard of house near the cul-de-sac,\nEnter through the front gate.",
    "School\nSide lawn of Harrington House you mow during detention.",
    "Vale\nIn the yard of the second 'Lawn Mowing' with the four bird baths",
    "Vale\nYard across the street from Tad's house.",
    "Vale\nNext to the front door of the house with the epic jump\non the back patio that sends you to the beach",
    "Vale\nInside the little shed in the park near the port-a-potty\nLeft one",
    "Vale\nInside the little shed in the park near the port-a-potty\nRight one",
    "Blue skies\nMain asylum grounds beside 'the watcher' statue.",
    "Vale\nFront porch of fenced-in house across the street from the mowing job house.\nJump the missing fence section on the west side of the house.",
    "Vale\nOffshore on the beach facing the sunken pirate ship.",
    "Vale\nNext to the front door of the house due east of the retirement home.",
    "Blue Skies\nOn the barge off the industrial docks.",
    "Vale\nNext to Tad's standalone garage.",
    "Vale\nOn the west side of the house across from Tad's garage.",
    "Vale\nBeside the front porch of the first house on the left after the bridge\nthat leads from Bullworth Town to Vale.",
    "Vale\nBesides the entrace to Bullworth Park. Near the retirment home.\nLeft side.",
    "Vale\nBesides the entrace to Bullworth Park.\nNear the retirment home.Right side.",
    "Vale\nBeside the southeast entrace to Bullworth Park."
];
