name: P3P Load Remover Checks
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - 'p3p/**'
      - '.cargo/**'
      - 'Cargo.toml'
      - 'Cargo.lock'

jobs:
  clippy:
    name: Check clippy lints
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Install Rust
        uses: hecrj/setup-rust-action@v2
        with:
          rust-version: 'stable'
          targets: 'wasm32-unknown-unknown'
          components: clippy

      - name: Run Clippy
        run: cargo clippy --package p3p-load-remover --all-features

  format:
    name: Check formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Install Rust
        uses: hecrj/setup-rust-action@v2
        with:
          components: rustfmt

      - name: Run cargo fmt
        run: cargo fmt --all -- --check
