name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"

permissions:
  contents: write

jobs:
  release:
    name: Build and release all autosplitters
    runs-on: ubuntu-latest

    steps:
      - name: Checkout commit
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Install Rust
        uses: hecrj/setup-rust-action@v2
        with:
          rust-version: stable
          targets: wasm32-unknown-unknown

      - name: Build workspace
        run: cargo build --workspace --locked --release

      - name: Move latest tag
        run: |
          git tag --force latest "${{ github.sha }}"
          git push --force origin latest

      - name: Update latest release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: latest
          name: Autosplitters (latest)
          generate_release_notes: false
          make_latest: true
          overwrite_files: true
          files: |
            target/wasm32-unknown-unknown/release/gta3_autosplitter.wasm
            target/wasm32-unknown-unknown/release/gta4_autosplitter.wasm
            target/wasm32-unknown-unknown/release/p3p_load_remover.wasm
            target/wasm32-unknown-unknown/release/p4g_load_remover.wasm
            target/wasm32-unknown-unknown/release/sr2_autosplitter.wasm
            target/wasm32-unknown-unknown/release/bully_autosplitter.wasm
